### ISSUE TITLE
[QUESTION] How to complie python whl package?

### ISSUE THREAD

**Issue by chencuber** [CVCUDA/CV-CUDA#111]
It seems that there is no description on how to compile python whl package on the "Build CV-CUDA" section of README?
<img width="847" alt="image" src="https://github.com/CVCUDA/CV-CUDA/assets/34364618/5b203923-0d0f-47a6-b603-c36308efa5cd">

**Comment by ElinLiu0** [comment]
Do not use that,i suggest to download the tar package the unpack it,the Python library you would need is in `$path/opt/nvidia/cvcuda0/lib/x86_64-linux-gnu/python`,there would two `.so` libraries.
Copy that to `$python_path/site-packages/` and run python to test it out.
In my case,it's working fine:
```bash
Python 3.8.5 (default, Sep  4 2020, 07:30:14)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cvcuda
>>> import nvcv
>>> cvcuda.as_tensor()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: as_tensor(): incompatible function arguments. The following argument types are supported:
    1. (buffer: nvcv.ExternalBuffer, layout: Optional[nvcv.TensorLayout] = None) -> nvcv.Tensor
    2. (image: nvcvpy::priv::Image) -> nvcv.Tensor

Invoked with:
```

**Comment by chencuber** [comment]
> Do not use that,i suggest to download the tar package the unpack it. ![image](https://user-images.githubusercontent.com/75596885/277115264-96b73deb-30ec-4f60-bf6a-f06dd51537b9.png)
> 
> The Python library you would need is in `$path/opt/nvidia/cvcuda0/lib/x86_64-linux-gnu/python`,there would two `.so` libraries. Copy that to `$python_path/site-packages/` and run python to test it out. In my case,it's working fine:
> 
> ```shell
> Python 3.8.5 (default, Sep  4 2020, 07:30:14)
> [GCC 7.3.0] :: Anaconda, Inc. on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import cvcuda
> >>> import nvcv
> >>> cvcuda.as_tensor()
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> TypeError: as_tensor(): incompatible function arguments. The following argument types are supported:
>     1. (buffer: nvcv.ExternalBuffer, layout: Optional[nvcv.TensorLayout] = None) -> nvcv.Tensor
>     2. (image: nvcvpy::priv::Image) -> nvcv.Tensor
> 
> Invoked with:
> ```

I just had to rebuild the project since its requirement of some software version is two high for deployment

**Comment by shiremathNV** [comment]
@chencuber - could you provide more details on the software versions that you are interested in seeing being supported?

**Comment by dlesage-nvidia** [comment]
@chencuber , see also https://github.com/CVCUDA/CV-CUDA/issues/138

We are currently working on refining our build system and artifact generation.
We intend to publish utilities to generate Python wheels as part of a future release.
We are tracking your feature request internally and will update that ticket as we have an ETA.
Thank you for your patience!

**Comment by bhaefnerNV** [comment]
Hi @chencuber,
Thank you for your interest in CVCUDA.
Since [release 0.6.0-beta](https://github.com/CVCUDA/CV-CUDA/releases/tag/v0.6.0-beta), we provide standalone python wheels, including tooling and documentation to generate them for python versions 3.8, 3.9, 3.10, and 3.11. The python wheels can be found under the same link above. If you'd like to build your own python wheels, this can automatically be triggered, when building CVCUDA in release mode, please see [here ](https://github.com/CVCUDA/CV-CUDA#build-from-source) for further details.
We will close this issue for now. Please feel free to reopen, if more questions arise.
