### ISSUE TITLE
[QUESTION]ERROR: Invalid elements batch = 18,really need help now!

### ISSUE THREAD

**Issue by ElinLiu0** [CVCUDA/CV-CUDA#155]
I'm trying to use `cvcuda.osd()` to accelerate bounding box render in my object detection pipeline.
Here is my code:
```python
# Apply non-maximum suppression to filter out overlapping bounding boxes
        indices = cv2.dnn.NMSBoxes(boxes,scores,self.confidenceThres,self.iouThres)
        
        bbox_list,text_list = [],[]
        
        for i in indices:
            box = boxes[i]
            score = scores[i]
            classIndex = class_ids[i]
            bbox_list.append(
                [cvcuda.BndBoxI(
                    box = tuple(box),
                    thickness = 2,
                    borderColor = tuple(self.colorPalette[classIndex].tolist()),
                    fillColor = (0,0,0,0)
                )]
            )
            labelX = box[0]
            labelY = box[1] - 10 if box[1] - 10 > 10 else box[1] + 10
            text_list.append(
                [cvcuda.Label(
                    utf8Text = '{}: {}'.format(self.classes[classIndex],str(score * 100)[0:5] + '%'),
                    fontSize = 1,
                    tlPos = (labelX,labelY),
                    fontColor = (255,255,0),
                    bgColor = tuple(self.colorPalette[classIndex].tolist())
                )]
            )

        # Draw the bounding boxes and labels on the image
        batch_bounding_boxes = cvcuda.Elements(elements=bbox_list)
        batch_text = cvcuda.Elements(elements=text_list)

        cvcuda.osd_into(frame_hwc,frame_hwc,batch_bounding_boxes)
        cvcuda.osd_into(frame_hwc,frame_hwc,batch_text)
```
And then cvcuda raised error like below:
```python
ERROR: Invalid elements batch = 18
Traceback (most recent call last):
  File "/home/elin/StudentBehaviorDetection/gpupipe/test.py", line 9, in <module>
    postprocessedImage = processor.processing(image)
  File "/home/elin/StudentBehaviorDetection/gpupipe/VideoProcessorGPUCV.py", line 150, in processing
    outputFrame = self.postProcess(frame,output)
  File "/home/elin/StudentBehaviorDetection/gpupipe/VideoProcessorGPUCV.py", line 126, in postProcess
    cvcuda.osd_into(frame_hwc,frame_hwc,batch_bounding_boxes)
RuntimeError: NVCV_ERROR_INVALID_ARGUMENT: (INVALID_DATA_SHAPE)
```
I don't know why this error has been raised,it's almost the deadline of my paper T_T.

**Comment by ElinLiu0** [comment]
Issue traced.The input Element shape should looks like [[[element]]] in my case.
Issue close.
